### ISSUE TITLE
Cannot find module './type.d.ts'

### ISSUE THREAD

**Issue by acuper** [szikszail/object-set-type#3] opened 2022-03-10 07:36 UTC
Seems latest release (2.2.0) is broken.

Cannot find module './type.d.ts'
Require stack:
- D:\WK\Projects\wkit\wkit-one-monorepo-clean\node_modules\object-set-type\object_set.js
- D:\WK\Projects\wkit\wkit-one-monorepo-clean\node_modules\object-set-type\index.js
- D:\WK\Projects\wkit\wkit-one-monorepo-clean\node_modules\@wk\aura-assert\collection.js
- D:\WK\Projects\wkit\wkit-one-monorepo-clean\node_modules\@wk\aura-assert\plugins\identical.js
- D:\WK\Projects\wkit\wkit-one-monorepo-clean\node_modules\@wk\aura-assert\index.js

**Comment by szikszail** [comment] 2022-03-10 07:49
@acuper the issue is fixed in v2.2.1
Please check it, and thank you for reporting this issue.

**Comment by acuper** [comment] 2022-03-10 07:55
I confirm, the issue is fixed in 2.2.1
Thanks @szikszail !

**Closed as completed** 2022-03-10 07:59 UTC
